# Generated by Django 4.1.3 on 2022-11-22 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myshop', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='catdb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
                ('description', models.CharField(blank=True, max_length=60, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='profile')),
            ],
        ),
        migrations.RemoveField(
            model_name='admindb',
            name='Email',
        ),
        migrations.RemoveField(
            model_name='admindb',
            name='Image',
        ),
        migrations.RemoveField(
            model_name='admindb',
            name='Name',
        ),
        migrations.RemoveField(
            model_name='admindb',
            name='Password',
        ),
        migrations.RemoveField(
            model_name='admindb',
            name='Username',
        ),
        migrations.AddField(
            model_name='admindb',
            name='email',
            field=models.EmailField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='admindb',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='profile'),
        ),
        migrations.AddField(
            model_name='admindb',
            name='name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='admindb',
            name='password',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='admindb',
            name='username',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
