# Generated by Django 4.1.3 on 2022-11-23 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myshop', '0002_catdb_remove_admindb_email_remove_admindb_image_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='prodb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
                ('price', models.CharField(blank=True, max_length=50, null=True)),
                ('quantity', models.IntegerField()),
                ('description', models.TextField(blank=True, max_length=160, null=True)),
                ('category', models.CharField(blank=True, max_length=50, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='profile')),
            ],
        ),
        migrations.AlterField(
            model_name='catdb',
            name='description',
            field=models.TextField(blank=True, max_length=160, null=True),
        ),
    ]
