# Generated by Django 4.1.3 on 2022-11-28 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myshop', '0003_prodb_alter_catdb_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='logdb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(blank=True, max_length=50, null=True)),
                ('password', models.CharField(blank=True, max_length=10, null=True)),
            ],
        ),
    ]
